<h1>Импорт библиотек

In [2]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [ ]:
import numpy as np


def sum_prod(X, V):
    n = X[0].shape[0]  # Предполагаем, что все матрицы имеют одинаковый размер (n, n)
    
    # Создаем начальный результирующий вектор размером (n, 1), заполненный нулями
    result = np.zeros((n, 1))
    
    # Перебираем пары (матрица, вектор) из списков X и V
    for matrix, vector in zip(X, V):
        # Умножаем текущую матрицу на соответствующий вектор и добавляем к результату
        result += np.dot(matrix, vector)  # np.dot выполняет матричное умножение
    
    # Возвращаем итоговый вектор (сумму всех произведений)
    return result


# Определим список матриц X
X = [
    np.array([[1, 2], [3, 4]]),      # Матрица 1 (размер 2x2)
    np.array([[5, 6], [7, 8]])       # Матрица 2 (размер 2x2)
]

# Определим соответствующий список векторов V
V = [
    np.array([[1], [1]]),            # Вектор 1 (размер 2x1)
    np.array([[2], [2]])             # Вектор 2 (размер 2x1)
]

# Вызов функции sum_prod и сохранение результата
result = sum_prod(X, V)

print(result)


Сумма произведений матриц на векторы:
[[25.]
 [37.]]


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [3]:
import numpy as np

def binarize(M, threshold):
    # Применяем условие, возвращаем матрицу из 0 и 1
    return (M > threshold).astype(int)

def run_tests():
    # Тест 1: простая матрица 2x2
    M1 = np.array([[0, 2], [3, 1]])
    threshold1 = 1
run_tests()

<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
def unique_rows(mat):
    return [np.unique(row).tolist() for row in mat]

def unique_columns(mat):
    
    #Возвращает уникальные элементы из каждого столбца матрицы.

    #Параметры:
    #mat (np.ndarray): входная матрица

    #Возвращает:
    #list of lists: список уникальных элементов для каждого столбца'''
    return [np.unique(mat[:, col]).tolist() for col in range(mat.shape[1])]


def run_tests():
    # Тестовая матрица
    mat = np.array([
        [1, 2, 2, 3],
        [4, 4, 5, 5],
        [6, 7, 7, 6]
    ])

    # Тест для уникальных элементов по строкам
    print("Тест уникальные элементы по строкам:", unique_rows(mat))
    # Ожидаемый результат: [[1, 2, 3], [4, 5], [6, 7]]

    # Тест для уникальных элементов по столбцам
    print("Тест уникальные элементы по столбцам:", unique_columns(mat))
    # Ожидаемый результат: [[1, 4, 6], [2, 4, 7], [2, 5, 7], [3, 5, 6]]

# Запуск тестов
run_tests()

Тест уникальные элементы по строкам: [[1, 2, 3], [4, 5], [6, 7]]
Тест уникальные элементы по столбцам: [[1, 4, 6], [2, 4, 7], [2, 5, 7], [3, 5, 6]]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here
import numpy as np

def chessboard_matrix(m, n, a, b):
    matrix = np.empty((m, n), dtype=type(a))  # создаём пустую матрицу указанного размера и типа a
    for i in range(m):
        for j in range(n):
            # Чередование значений a и b в зависимости от индексов
            matrix[i, j] = a if (i + j) % 2 == 0 else b
    return matrix

def run_tests():
    # Тест 1: матрица 3x3, значения 1 и 0
    print("Тест 1:\n", chessboard_matrix(3, 3, 1, 0))
    # Ожидаемый результат:
    # [[1, 0, 1],
    #  [0, 1, 0],
    #  [1, 0, 1]]
run_tests()

Тест 1:
 [[1 0 1]
 [0 1 0]
 [1 0 1]]


<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [9]:
import numpy as np

def chess(m, n, a, b):
    matrix = np.empty((m, n), dtype=type(a))  # создаём пустую матрицу указанного размера и типа a
    for i in range(m):
        for j in range(n):
            # Чередование значений a и b в зависимости от индексов
            matrix[i, j] = a if (i + j) % 2 == 0 else b
    return matrix

# Тестирование функции
def run_tests():
    # Тест 1: матрица 3x3, значения 1 и 0
    print("Тест 1:\n", chessboard_matrix(3, 3, 1, 0))
    # Ожидаемый результат:
    # [[1, 0, 1],
    #  [0, 1, 0],
    #  [1, 0, 1]]
run_tests()

Тест 1:
 [[1 0 1]
 [0 1 0]
 [1 0 1]]


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [10]:
from PIL import Image, ImageDraw

def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Создаём изображение с фоновым цветом
    img = Image.new("RGB", (n, m), background_color)
    draw = ImageDraw.Draw(img)

    # Вычисляем координаты для центрирования прямоугольника
    top_left = ((n - a) // 2, (m - b) // 2)
    bottom_right = (top_left[0] + a, top_left[1] + b)
    
    # Рисуем прямоугольник
    draw.rectangle([top_left, bottom_right], fill=rectangle_color)
    return img


def run_tests():
    # Тест 1: Прямоугольник на изображении 200x200, с размерами 100x50, синим фоном и красным прямоугольником
    img1 = draw_rectangle(100, 50, 200, 200, (255, 0, 0), (0, 0, 255))
    img1.show(title="Прямоугольник")

run_tests()

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
import numpy as np

def analyze_time_series(series, p):
    # Преобразуем ряд в массив numpy для удобства
    series = np.array(series)

    # 1. Математическое ожидание
    mean = np.mean(series)
    
    # 2. Дисперсия
    variance = np.var(series)
    
    # 3. Среднеквадратическое отклонение (СКО)
    std_dev = np.std(series)
    
    # 4. Локальные максимумы и минимумы
    local_maxima = []
    local_minima = []
    for i in range(1, len(series) - 1):
        if series[i] > series[i - 1] and series[i] > series[i + 1]:
            local_maxima.append((i, series[i]))  # (индекс, значение)
        elif series[i] < series[i - 1] and series[i] < series[i + 1]:
            local_minima.append((i, series[i]))  # (индекс, значение)

    # 5. Скользящее среднее с размером окна p
    moving_average = np.convolve(series, np.ones(p) / p, mode='valid')

    # Возвращаем результаты в виде словаря
    return {
        "mean": mean,
        "variance": variance,
        "std_dev": std_dev,
        "local_maxima": local_maxima,
        "local_minima": local_minima,
        "moving_average": moving_average
    }


<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
import numpy as np

def one_hot_encoding(labels, num_classes=None):

    # Преобразуем labels в numpy-массив для удобства
    labels = np.array(labels)

    # Если num_classes не передан, определим его как максимальное значение метки + 1
    if num_classes is None:
        num_classes = np.max(labels) + 1

    # Создаём матрицу с нулями и затем ставим единицы в нужных местах
    one_hot_matrix = np.zeros((len(labels), num_classes), dtype=int)
    one_hot_matrix[np.arange(len(labels)), labels] = 1

    return one_hot_matrix

# Тестирование функции
labels = [0, 2, 3, 0]
one_hot_result = one_hot_encoding(labels)

# Выводим результат
print("One-hot encoding:\n", one_hot_result)